In [2]:
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [6]:
from transformers import BertModel, BertForMaskedLM, BertConfig,BertTokenizer, PreTrainedEncoderDecoder

# Initializing a BERT bert-base-uncased style configuration
configuration = BertConfig()

# Initializing a model from the bert-base-uncased style configuration
model = BertModel(configuration)

# Accessing the model configuration
configuration = model.config

In [69]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')
input_ids = torch.tensor(tokenizer.encode("raise an exception of class ValueError, with string \"Key '%s' not found\" as argument, where '%s' is substituted for key.", add_special_tokens=True)).unsqueeze(0)  # Batch size 1
# input_ids[0,7] = tokenizer.mask_token_id
# input_ids = input_ids[:,:-1]
# input_ids[0,9] = tokenizer.mask_token_id
print([tokenizer.convert_ids_to_tokens([predicted_index]) for predicted_index in input_ids[0]])
outputs = model(input_ids, masked_lm_labels=input_ids)
loss, prediction_scores = outputs[:2]

[['[CLS]'], ['raise'], ['an'], ['exception'], ['of'], ['class'], ['value'], ['##er'], ['##ror'], [','], ['with'], ['string'], ['"'], ['key'], ["'"], ['%'], ['s'], ["'"], ['not'], ['found'], ['"'], ['as'], ['argument'], [','], ['where'], ["'"], ['%'], ['s'], ["'"], ['is'], ['substituted'], ['for'], ['key'], ['.'], ['[SEP]']]


In [23]:
import json
json.dumps({None: None})

'{"null": null}'

In [21]:
import pprint as pp
model.state_dict().keys()

odict_keys(['encoder.embeddings.word_embeddings.weight', 'encoder.embeddings.position_embeddings.weight', 'encoder.embeddings.token_type_embeddings.weight', 'encoder.embeddings.LayerNorm.weight', 'encoder.embeddings.LayerNorm.bias', 'encoder.encoder.layer.0.attention.self.query.weight', 'encoder.encoder.layer.0.attention.self.query.bias', 'encoder.encoder.layer.0.attention.self.key.weight', 'encoder.encoder.layer.0.attention.self.key.bias', 'encoder.encoder.layer.0.attention.self.value.weight', 'encoder.encoder.layer.0.attention.self.value.bias', 'encoder.encoder.layer.0.attention.output.dense.weight', 'encoder.encoder.layer.0.attention.output.dense.bias', 'encoder.encoder.layer.0.attention.output.LayerNorm.weight', 'encoder.encoder.layer.0.attention.output.LayerNorm.bias', 'encoder.encoder.layer.0.intermediate.dense.weight', 'encoder.encoder.layer.0.intermediate.dense.bias', 'encoder.encoder.layer.0.output.dense.weight', 'encoder.encoder.layer.0.output.dense.bias', 'encoder.encoder.la

In [67]:
print(prediction_scores.shape)
print()
max_ids = torch.argsort(prediction_scores[0,7], dim=0, descending=True)[:5]
print(max_ids)
[tokenizer.convert_ids_to_tokens([predicted_index]) for predicted_index in max_ids]

torch.Size([1, 8, 30522])

tensor([1000, 1012, 1007, 1996, 1006])


[['"'], ['.'], [')'], ['the'], ['(']]

In [52]:
print(prediction_scores.shape)
print()
max_ids = torch.argsort(prediction_scores[0,9], dim=0, descending=True)[:5]
print(max_ids)
[tokenizer.convert_ids_to_tokens([predicted_index]) for predicted_index in max_ids]

torch.Size([1, 12, 30522])

tensor([2665, 3730, 3585, 3652, 3376])


[['green'], ['soft'], ['golden'], ['growing'], ['beautiful']]

In [15]:
predicted_index = torch.argmax(prediction_scores[0], dim=1)[1].item()
predicted_token = tokenizer.convert_ids_to_tokens([predicted_index])[0]
predicted_token

'.'

In [9]:
prediction_scores.shape

torch.Size([1, 8, 30522])

In [10]:
input_ids

tensor([[  101,  7592,  1010,  2026,  3899,  2003, 10140,   102]])